name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [darwin, linux, windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install NPM packages
        run: cd ui && yarn install --frozen-lockfile

      - name: Build Release Binary
        run: |
          GOOS=${{ matrix.goos }} GOARCH=amd64 make build
          tar -czvf asynqmon_${{ github.ref_name }}_${{ matrix.goos }}_amd64.tar.gz asynqmon

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: asynqmon_${{ github.ref_name }}_${{ matrix.goos }}_amd64.tar.gz
